### ISSUE TITLE
Add constants

### ISSUE THREAD

**Issue by fvictorio** [Huemul/chimi#21]
It would be useful and (I think) easy to add a `constants` option to the configuration, similar to the `dependencies` option.

I'm thinking in being able to validate the readme in [type-detect](https://github.com/chaijs/type-detect), that uses an undefined `callback` variable. This would be easy to fix doing:

```
constants: {
  callback: '() => {}'
}
```

What do you think?

**Comment by gillchristian** [comment]
Yeah, for cases like type-detect one makes sense.

It would then just interpolate the value, right? Like how [webpack's define plugin](https://webpack.js.org/plugins/define-plugin/) works.

**Comment by fvictorio** [comment]
Uhm, I'd just prepend the declarations, after the dependencies. It seems easier and less problematic.
