### ISSUE TITLE
Setup testing flow

### ISSUE THREAD

**Issue by gillchristian** [Huemul/chimi#25]
We should setup a proper test flow (both unit & integration).

We already have Jest in place ( #22 ) and the [`example/` directory](https://github.com/Huemul/chimi/tree/master/example) to manually do integration.

We should automate this a bit more, even add CI.

**Comment by fvictorio** [comment]
I looked for something to perform end-to-end tests on CLI apps, but nothing convinced me.

- [Nixt](https://github.com/vesln/nixt) seems nice, but looks abandoned.
- [Cram](https://bitheap.org/cram/) seems cool for simpler things, I don't think it's going to be a good fit for chimi.
- [Aruba](https://github.com/cucumber/aruba) has hidden its documentation really well, or it doesn't have one.

Honestly, I'm leaning towards some ad hoc bash scripts that diff with some text file per fixture. Poor man's snapshots, in other words.

**Comment by fvictorio** [comment]
See #27

**Comment by gillchristian** [comment]
Cool, thanks! :muscle:

I took a look at how Jest tests itself, and it's similar to your approach in #27 (check this [npm script](https://github.com/facebook/jest/blob/master/package.json#L85-L96) and the [file](https://github.com/facebook/jest/blob/master/package.json#L94) it runs). We could refine it a bit and maybe even abstract it to a separated package. Wdyt ?

**Comment by gillchristian** [comment]
I found more interesting things in the Jest tests.

This [script](https://github.com/facebook/jest/blob/master/package.json#L85) runs Jest itself which runs all the tests in the [`packages/`](https://github.com/facebook/jest/tree/master/packages) and [`integration_tests/`](https://github.com/facebook/jest/tree/master/integration_tests).

I will take a deeper look later into it to find more ideas.

**Comment by gillchristian** [comment]
#27
