### ISSUE TITLE
Alias dependencies

### ISSUE THREAD

**Issue by gillchristian** [Huemul/chimi#33]
It would be nice to be able to alias dependencies imports/requires to local files.

In `trae` we could alias it to the local build file:

```
// .chimirc
{
  "alias": {
    "trae": "./dist/trae.umd.min.js"
  }
}
```

```js
const trae = require('trae')

// when the snippet runs is converted to

const trae = require('./dist/trae.umd.min.js')
```

**Comment by fvictorio** [comment]
We already support that, don't we?

**Comment by gillchristian** [comment]
No. We support adding dependencies, but not alias the ones that are already there.

**Comment by gillchristian** [comment]
#41
